### ISSUE TITLE
JSON ERROR

### ISSUE THREAD

**Issue by MikeBateman** [appfeel/analytics-google-adid#4]
Hi, 
### ANDROID ISSUE

I have created a fresh cordova app and added your plugin.
When i run this command:
<code>
 cordova.exec(Success, Fail, 'GAPluginAdId', 'startAdIdTrackerWithId', 'UA-XXXXXXXX-X');
</code>

The Fail callback is returned with a error of JSON Error? If i ignore this error and continue to request a ADID it seems to give a  ADID back? is this ADID going to be correct?
Any ideas what the JSON Error is?

**Comment by appfeel** [comment]
Hi @MikeBateman 

Normally you should call

```
analytics.startAdIdTrackerWithId('UA-XXXXXXXX-X', Success, Fail);
```

But if you want to do it with cordova, you should do it like this:

```
cordova.exec(success, error, 'GAPluginAdId', 'startAdIdTrackerWithId', [id]);
```

**Comment by MikeBateman** [comment]
Thanks @appfeel,
Just a thought:
Do i need call <code>startAdidTrackerWithId</code> before calling <code>getAdid</code>? I'm not sure why the Google analytics tracking code is required to get the ADID ?

Cheers

**Comment by appfeel** [comment]
:) @MikeBateman not really: `getAdId` just returns the device adId (and it just does it)

`startAdidTrackerWithId(...)` tells the tracker to use adId to collect data in successive GA tracking calls.
