### ISSUE TITLE
com.android.dex.DexIndexOverflowException: method ID... + how to fix

### ISSUE THREAD

**Issue by Ziv-Barber** [appfeel/analytics-google-adid#7]
On build.gradle:

Change:

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    ...
    compile "com.google.android.gms:play-services:+"
    // SUB-PROJECT DEPENDENCIES END
}

To:

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DDDEPENDENCIES START
    ...
    // compile "com.google.android.gms:play-services:+"
    compile "com.google.android.gms:play-services-analytics:+"
    // SUB-PROJECT DDDEPENDENCIES END
}

It's NOT possible to add ALL of Google Play Services.... so we must add only play-services-analytics.

**Comment by miqmago** [comment]
This is fixed in the new version
